services:
  - docker

install:
  - curl https://cli-assets.heroku.com/install.sh | sh

script:


  - > # DEFINICION DE VARIABLES Y FUNCIONES DE CONTROL

    export step=0;
    export totalSteps=6;

    stepInit () {
      step=$((step + 1));
      echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - $1 ----- \n";
    };

    stepFinish () {
      if [[ "$1" = "1" ]]
        then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - $2 ----- \n\n\n\n";
        exit 1;
      fi;
      then echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - $2 ----- \n\n\n\n";
    };




  - > # DESCARGA DE IMAGEN DE DOCKERHUB

    stepInit "DESPLIEGUE A DOCKERHUB";

    echo "$DOCKER_PASSWORD" | docker login -u $ORGANIZATION --password-stdin;
    docker pull $ORGANIZATION/payroll-server:latest

    stepFinish $? "DESPLIEGUE A DOCKERHUB";




  - > # DESPLIEGUE A HEROKU REGISTRY

    stepInit;

    echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com;
    docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_PRODUCTION/web;
    docker push registry.heroku.com/$HEROKU_APP_PRODUCTION/web;

    stepFinish $?;




  - > # RELEASE DE HEROKU APP PRODUCTION

    stepInit;

    heroku container:release web --app=$HEROKU_APP_PRODUCTION; 

    stepFinish $?;


